### ISSUE TITLE
README рекомендации

### ISSUE THREAD

**Issue by ardashev-dev** [AkelonDev/OpenXML#6]
Хорошо бы добавить информацию как применять этот код. Что откуда копировать, какие методы дорабатывать, а какие не стоит трогать. 
Также можно добавить про особенности хранения шаблонов в БД.

**Comment by Regdota** [comment]
Изменен текст блока "Варианты расширения функциональности на проектах". Описано самое простое использование функций решения. и рекомендация не дорабатывать приватные функции.
По созданию шаблона в самом конце добавлено: "Тело документа хранится в SQL-запросе стройкой base64."
